### ISSUE TITLE
crashes a email confirmation

### ISSUE THREAD

**Issue by lost-hope** [aslafy-z/ptc-account-generator#1]
Hi 
first of all: Great tool for making ptc accounts
but at the email veryfication the tool crashes:

> npm start
> 
>  ptc-account-generator@0.0.0 start /home/soeren/pokemon/ptc/ptc-account-generator
>  node ./index.js
> 
> Generating identity...
> { email: '45i8qq+9rabs0uchmqx8@sharklasers.com',
>   username: 'JadeAdam983934',
>   password: 'PJadeAdam983934',
>   date_of_birdth: '1995-02-13',
>   emailAccount: 
>    { email_addr: 'zbjigdfz@guerrillamailblock.com',
>      email_timestamp: 1469606382,
>      alias: '45i8qq+9rabs0uchmqx8',
>      sid_token: 'dopffbjce67l0bmc6r1vsv6ii7' } }
> Retrieving proxy...
> Found proxy: http://92.222.114.159:3128
> PLC Account creation...
> Waiting for email confirmation...
> Email received! => Verify your email
> { message: 'navigation error',
>   code: -300,
>   details: 'ERR_INVALID_URL',
>   url: 'Verify your email' }

hope you can fix this
the accounts are usable, but restarting the tool every time is a little bit annoing ;D

**Comment by aslafy-z** [comment]
Mmh, I couldn't reproduce this bug :/
Will investigate.

From now, if you want to batch generate, you can use a bash loop: 
`for i in $(seq 1 20); do npm start; done` to generate 20 accounts

**Comment by Aaranaw** [comment]
I am also getting this exact same message when I run from a cmd prompt on windows.

C:\Users\Localadmin\Desktop\ptc-account-generator-master>npm start

> ptc-account-generator@0.0.0 start C:\Users\Localadmin\Desktop\ptc-account-generator-master
> node ./index.js

Generating identity...
{ email: '45pgwd+6gp7cdmlkwofk@sharklasers.com',
  username: 'JadeCollet8842',
  password: 'PJadeCollet8842',
  date_of_birdth: '1993-11-18',
  emailAccount:
   { email_addr: 'gfqlcacz@guerrillamailblock.com',
     email_timestamp: 1469719749,
     alias: '45pgwd+6gp7cdmlkwofk',
     sid_token: 'aouuaj1hc3g5563v59f62tkkq7' } }
Retrieving proxy...
Found proxy: http://92.222.114.159:3128
PLC Account creation...
Waiting for email confirmation...
Email received! => Verify your email
{ message: 'navigation error',
  code: -300,
  details: 'ERR_INVALID_URL',
  url: 'Verify your email' }

C:\Users\Localadmin\Desktop\ptc-account-generator-master>

**Comment by kornbed** [comment]
I got the same error too on windows...

C:\Users\Admin\Documents\GitHub\ptc-account-generator>npm start

> ptc-account-generator@0.0.0 start C:\Users\Admin\Documents\GitHub\ptc-account-generator
> node ./index.js

Generating identity...
{ email: '4663sb+4t0pb2ldmo7tk@sharklasers.com',
  username: 'ThomasDurand575891',
  password: 'PThomasDurand575891',
  date_of_birdth: '1987-12-25',
  emailAccount:
   { email_addr: 'qwxqygea@guerrillamailblock.com',
     email_timestamp: 1470036078,
     alias: '4663sb+4t0pb2ldmo7tk',
     sid_token: '95up1o5inp0htoqr57dv44g2f5' } }
Retrieving proxy...
Found proxy: http://176.31.99.80:2222
PLC Account creation...
Waiting for email confirmation...
Email received! => Verify your email
{ message: 'navigation error',
  code: -300,
  details: 'ERR_INVALID_URL',
  url: 'Verify your email' }

**Comment by Mexflubber** [comment]
Was anybody able to fix it ?? There's not much documentation on node-guerrilla, I'm also getting the same error.

**Comment by aslafy-z** [comment]
It seems that node-guerrilla returns a bad url, and trying to load it un electron is throwing this ERR_INVALID_URL.

It couldn't reproduce it :/

**Comment by aslafy-z** [comment]
@Xide, can you take à look ?

**Comment by nmo0ory** [comment]
any news on how can i fix it ? i have the same problem is there any other website for email you can use ?

**Comment by nmo0ory** [comment]
maybe you can cheek any other email service ad replace it with the one you are useing maybe it will work, or is there any way you can make same trick with the google email ? and add like + / ! # on the email and all will be on the same email because google don't cheek the sign and also the ptc don't cheek it as well so you can make many account with just one email from google, but is there any way you can access it to auto confirm the account i don't know about that

**Comment by timlinde** [comment]
Found the problem. It seems to be a bug in the node-guerrilla module. After allot of debugging i had to change:
node_modules/node-guerrilla/lib/index.js
line 105
CHANGE:
`return link_text.resolve($("a:contains(" + contains_text + ")").text());`
TO:
`return link_text.resolve($("a:contains(" + contains_text + ")").attr("href"));`

**Comment by Mexflubber** [comment]
Working like a charm !! Thanks @timlinde. I wanted to do a pull request but since it is a dependency it would be harder as package is not in project.

**Comment by aslafy-z** [comment]
Please do so: https://github.com/rjferguson21/node-guerrilla
If his not answering i'll support it myself by forking it.

Or maybe we can use this one:
https://github.com/RedRiverSoftware/rr-guerrillamail

**Comment by aslafy-z** [comment]
I made a PR to node-guerrilla maintainer.
meanwhile, i'm using https://github.com/aslafy-z/node-guerrilla and it should resolve this bug.

Please re-clone/pull to confirm that it's working.
