### ISSUE TITLE
npm WARN/ERR! during npm install

### ISSUE THREAD

**Issue by Aaranaw** [aslafy-z/ptc-account-generator#2]
Testing this on a debian wheezy box, receive the following whilst running >npm install

npm WARN package.json ptc-account-generator@0.0.0 No repository field.
npm ERR! registry error parsing json
npm WARN engine nightmare@2.5.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm ERR! registry error parsing json
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN engine punycode@2.0.0: wanted: {"node":">=6"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})

**Comment by aslafy-z** [comment]
You are using a old version of nodejs. Please upgrade to nodejs 4.0
