### ISSUE TITLE
Special chars doesn't work for me

### ISSUE THREAD

**Issue by Chippi** [aslafy-z/ptc-account-generator#3]
Accounts generated with special chars doesn't work.

**Comment by aslafy-z** [comment]
Are you talking about special chars in username ?
I switched from French names to US names, it should be better.
If you want a generated names filter, pr are welcomes.

**Comment by Chippi** [comment]
Yep, it was because of FR, works perfect now!

**Comment by aslafy-z** [comment]
Nice ! Let me know if someone encounter thid bug again :)
