### ISSUE TITLE
Majority of accounts can't login

### ISSUE THREAD

**Issue by timlinde** [aslafy-z/ptc-account-generator#4]
After creating 10 accounts, only 2-3 of them are actually possible to login with. The other get this error on the pokemon site:
"Oops! It seems that Pokemon.com has had an unexpected error. Don't worry; the site administrators have already been notified and they'll try to have the problem fixed soon."

Anyone else also has this problem?
Just too much traffic since the api came back up?

**Comment by nmo0ory** [comment]
same here

**Comment by timlinde** [comment]
https://www.reddit.com/r/pokemongodev/comments/4wk3e4/psa_new_pogo_accounts_have_to_accept_tos_ingame/

Might be this?

**Comment by aslafy-z** [comment]
This is it, you can use this to fix it : https://github.com/TachyonRSA/PoGoTos

This will probaly be added in the next update, unless someone devotes to making a pr :D
