### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by nmo0ory** [aslafy-z/ptc-account-generator#5]
hello,
how can i make a loop 
is there any way to make "npm start" loop again and again with some limit i set or without any limit ?

**Comment by timlinde** [comment]
`for i in $(seq 1 20); do npm start; done` to generate 20 accounts

**Comment by nmo0ory** [comment]
i am using windows where should i add this ? i try it on the cmd but it won't work

**Comment by aslafy-z** [comment]
I'm not a windows man, but google is our friend.

`for /l %%X in (1,1,20) do (npm start)`

This should generate 20 accounts
