### ISSUE TITLE
account creation does not work for me

### ISSUE THREAD

**Issue by Snake4life** [aslafy-z/ptc-account-generator#6]
root@ubuntu:~/PTC/ptc-account-generator# nodejs index.js
Generating identity...
email:          475yk4+5txllc8b8y0yw@sharklasers.com
username:       JosefineImbriale2506
password:       PJosefineImbriale2506
date_of_birdth: 1982-12-06
emailAccount:
  email_addr:      bgkyycby@guerrillamailblock.com
  email_timestamp: 1470630057
  alias:           475yk4+5txllc8b8y0yw
  sid_token:       t70cnn9ltr3l66fri2kdevi7q2
Retrieving proxy...
Found proxy: http://52.90.42.177:8083
PLC Account creation...

after this I get no error + account is not created, is it broken only for me?

**Comment by Snake4life** [comment]
I triggered ptc-account-generator.js and got this

[http://pastebin.com/yWjbiqXn](http://pastebin.com/yWjbiqXn)

I think something with ES6 related dunno, reinstalled node module 6times now with different nodejs versions (4 and 6)

**Comment by aslafy-z** [comment]
Is the electron app loading pokemon.com website opening ? 
I think they blocked temporarly new accounts, i'm getting this: 

```
With the exciting launch of Pokémon GO, there’s an overwhelming demand for access to Pokémon Trainer Club accounts, including new accounts, profile changes, and password/username retrieval. Our team is hard at work improving support for these features. Until the work is complete, for a brief time, we’ll be limiting the amount of access to these features. Please refresh your browser and try again.
```

About your second post:
This is a regular behavior, index.js must be loaded to use babel.
Please use `npm start` instead of `node`.

**Comment by Snake4life** [comment]
ok now I get it, I used a linux server, that was the problem, with nodejs portable on windows its working now.

nvm that there is a window that pops up

**Comment by aslafy-z** [comment]
I'll probably make it working with phantomjs or something else that doesnt needs X :)

Closing this.
